0.6.1-beta.1
lingbopro/soberjs-vscode pull request #11
Opened 2024-10-06 02:15 UTC by Minemetero

Working in prograss...

2024-10-06 03:29 UTC, lingbopro requested changes

2024-10-06 03:29 UTC, lingbopro commented on custom-data/components.html-data.json
> +      "description": "**文本框 Text Field**\n\n`Text Field` 是一个容器组件，可以在内部放置 `input` 和 `textarea` 元素。推荐使用 `label` 属性来替代 `placeholder`，从而在表单交互中提升可访问性。\n\n```html\n<s-text-field>\n  <input type=\"text\" pl
改哪了？

（这行太长了没diff）

2024-10-06 03:29 UTC, lingbopro commented on custom-data/components.html-data.json
> +      ],
貌似自定义HTML数据不支持事件名吧…可以看一下VSCode的文档

2024-10-06 03:29 UTC, lingbopro commented on custom-data/components.html-data.json
>        ],
CSS变量在另一个文件

2024-10-06 03:29 UTC, lingbopro commented on custom-data/components.html-data.json
> +    },
？

2024-10-06 03:29 UTC, lingbopro commented on custom-data/components.html-data.json
> +          "url": "https://github.com/apprat/sober/blob/main/src/picker-item.ts"
Picker Item 没有独立的文件

2024-10-06 03:38 UTC, Minemetero commented on custom-data/components.html-data.json
> +      ],
支持是支持

2024-10-06 03:38 UTC, Minemetero commented on custom-data/components.html-data.json
> +      ],
`如果您想在扩展程序中包含事件文档，您可能需要通过工具提示或其他语言服务配置手动处理它`

2024-10-06 04:49 UTC, lingbopro commented on custom-data/components.html-data.json
> +      ],
> `如果您想在扩展程序中包含事件文档，您可能需要通过工具提示或其他语言服务配置手动处理它`

`手动处理`，JSON架构里好像并没有`events`字段？

2024-10-06 04:50 UTC, lingbopro commented
我觉得这个可以`0.7.0`了

2024-10-06 07:46 UTC, Minemetero commented
> 我觉得这个可以`0.7.0`了，就加了个patch版本号有点少感觉

lol 行

2024-10-06 07:47 UTC, Minemetero commented
> 我觉得这个可以`0.7.0`了，就加了个patch版本号有点少感觉

你dev调试一下 看看有什么问题

2024-10-06 09:32 UTC, lingbopro commented on custom-data/components.html-data.json
> +        },
这个东西是只读属性吧，不用写在这里，而且也没`type`字段吧

2024-10-06 09:32 UTC, lingbopro commented on custom-data/components.html-data.json
> +          ]
这里可以直接用我写在最后面的`valueSet`（`boolean`）

2024-10-06 09:32 UTC, lingbopro commented on package.json
> +  "version": "0.6.1",
emmm没改版本号

2024-10-06 10:36 UTC, lingbopro requested changes

2024-10-06 10:36 UTC, lingbopro commented on package.json
> +  "version": "0.6.1",
```suggestion
  "version": "0.7.0",
```

2024-10-06 10:36 UTC, lingbopro commented on custom-data/components.html-data.json
> +          ]
```suggestion
          "valueSet": "boolean"
```

2024-10-06 10:36 UTC, lingbopro commented on custom-data/components.html-data.json
> +          "defaultValue": "false"
```suggestion
          "valueSet": "boolean"
```

2024-10-06 10:36 UTC, lingbopro commented on custom-data/components.html-data.json
> +          "defaultValue": ""
`type`和`defaultValue`在这个架构里并不存在吧

2024-10-06 10:36 UTC, lingbopro commented on custom-data/components.html-data.json
> +          ]
```suggestion
          "valueSet": "boolean"
```

2024-10-06 10:36 UTC, lingbopro commented on CHANGELOG.md
> +## v0.6.1
```suggestion
## v0.7.0
```

2024-10-06 10:36 UTC, lingbopro commented on custom-data/components.css-data.json
> +      "default": "4px",
还是，架构里并没有此字段，写在`description`里就行了

2024-10-07 00:49 UTC, Minemetero commented on custom-data/components.html-data.json
> +        },
![image_2024-10-07_094858455](https://github.com/user-attachments/assets/ee1d5486-cad7-4e63-a7b8-dc8fc8505eed)
这部写得清清楚楚type Item[]

2024-10-07 00:52 UTC, lingbopro commented on custom-data/components.html-data.json
> +        },
那你写`description`里吧，你这么写好像也没效果？

2024-10-07 01:10 UTC, Minemetero commented on custom-data/components.html-data.json
> +          "defaultValue": ""
等我回家改

2024-10-07 01:31 UTC, lingbopro commented
我打算更新一下工作流，这样手动发布还是太麻烦了

2024-10-07 02:07 UTC, Minemetero commented
> 我打算更新一下工作流，这样手动发布还是太麻烦了

听上去很不错，自动发布

2024-10-07 03:23 UTC, lingbopro commented
<img width="423" alt="image" src="https://github.com/user-attachments/assets/6a3e36d3-d421-48ea-9b29-148a07783a2b">

我要push了

2024-10-07 03:31 UTC, lingbopro approved these changes
我觉得差不多了

2024-10-07 04:16 UTC, Minemetero commented
看你改了改应该可以Merge了

2024-10-07 04:32 UTC, Minemetero commented on .prettierrc
这个可以CleanUp 不要了吧

2024-10-07 05:11 UTC, lingbopro commented on .prettierrc
还是留着吧，不然格式化不对

2024-10-07 05:12 UTC, lingbopro commented
我再测试一下

2024-10-07 07:00 UTC, Minemetero commented on .prettierrc
问题是我不用Prettier

2024-10-07 07:42 UTC, lingbopro commented on .prettierrc
我觉得留着比较好，用Prettier的话格式也能统一

2024-10-07 07:46 UTC, Minemetero commented on .prettierrc
行吧

2024-10-07 08:01 UTC, Minemetero commented
> 我再测试一下

测试测试可以合并了吧

2024-10-07 08:33 UTC, lingbopro commented
差不多可以并了

2024-10-07 08:36 UTC, lingbopro commented
那我就合并了

2024-10-07 08:37 UTC, merged

2024-10-07 08:38 UTC, lingbopro commented
![image](https://github.com/user-attachments/assets/7cca7161-5961-4fc7-ac88-9d40c48a0bb4)

见证奇迹的时刻（bushi

2024-10-07 08:39 UTC, lingbopro commented
???

2024-10-07 10:45 UTC, Minemetero commented
66666